### ISSUE TITLE
Cloudflare as a Risk

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/.github#111]
I've received a few emails from Cloudflare sales but didn't make time to speak with them. Turns out they are developing a reputation for extortion. It's something we should have a plan for/think about. I'm expecting them to pull the plug just when we start onboarding partners. 

- https://robindev.substack.com/p/cloudflare-took-down-our-website
- https://www.youtube.com/watch?v=8zj7ei5Egk8

**Comment by whilefoo** [comment]
Right now we're using Cloudflare only for the kernel and plugins, right? The only thing that stops us from quickly switching over is the KV. 
We could use a database and [hono.dev](https://hono.dev/) which would make it simple to switch but of course the priority right now is to ship v2

**Comment by 0x4007** [comment]
In the context of the bot, yes its basically just for Workers. However we also do handle all of our DNS settings on there for our domains which can be complex to fix if we need to hastily move off. Perhaps we should set up redundant serverless infra and then we can switch faster when they pull the rug. 

I already have ubq.fi hosted on a separate registrar so it shouldn't be too difficult to point the nameservers elsewhere.

**Comment by gentlementlegen** [comment]
It is quite ludicrous. But they seem to target big whales because they expect to make money out of it. I do not think we would be a target before reaching quite a heavy payload.

I can't think of many alternatives, but one I could mention is Azure services with https://azure.microsoft.com/en-us/products/functions . They are usually quite generous on the usage, and I never heard such extortion scenarios. And on the plus side, we would stick to Microsoft products, since we already use GitHub quite extensively.

**Comment by 0x4007** [comment]
> We could use a database and [hono.dev](https://hono.dev/) which would make it simple to switch

Pretty interesting although I'm very cautious to introduce new technologies. Fortunately they emphasize being small and performant which implies it is probably simple to use.

**Comment by 0x4007** [comment]
https://x.com/levelsio/status/1800512938345930952?s=46&t=bdMjuqzO5LYxLUsloRROxQ

**Comment by gentlementlegen** [comment]
Since we are now using `hono` in the SDK I believe it should be much easier to switch runtime (it supports Cloudflare, Fastly, Deno, Bun, AWS, or Node.js) with the same codebase. The transition should be smoother if tomorrow we want to self host or move to AWS for some reason. What it would take is a change in the deployment actions we use, but hopefully very little changes in the code should be enough.

Maybe we should consider also equipping the Kernel with hono to allow the kernel to run anywhere without relying on wrangler as well.

**Comment by gentlementlegen** [comment]
I think this can be closed since we are now using `hono` in the kernel which allows us to change runtime easily.

**Comment by 0x4007** [comment]
How about for plugins?

**Comment by whilefoo** [comment]
> How about for plugins?

Plugins also use `hono` so we can switch easily.

**Comment by 0x4007** [comment]
@gentlementlegen how long did it take to fix the kernel?

**Comment by 0x4007** [comment]
You can set the hours, link the relevant pulls, and collect credit

**Comment by 0x4007** [comment]
1 2 or 4 hours is basically my question.

**Comment by gentlementlegen** [comment]
2 seems fair, we are only applying this to the kernel at the moment correct (not the plugins)?

**Comment by 0x4007** [comment]
This implies we don't need to rely on cloud flare anymore so yes it includes the plugins.

**Comment by whilefoo** [comment]
I think we should first test Azure on the kernel to see how it performs.

**Comment by gentlementlegen** [comment]
Merging this in tomorrow calmly and making sure that the environment is set up.

**Comment by gentlementlegen** [comment]
Up and running at https://ubiquity-os.azurewebsites.net (for the dev branch of https://github.com/ubiquity-os/ubiquity-os-kernel).
