### ISSUE TITLE
Sync ERC20 Permit and ERC721 Types System Wide

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#98]
This is a large project because it requires two tasks:

1. Designing a robust and sensible schema for all permits in our system.
2. Updating the code across all of our repositories. This will require updating the database to accomodate the updated schema as well. 

This is especially relevant in the: 
1. pay.ubq.fi interface
2. the UbiquiBot permit generation code
3. audits app
4. nft-rewards repository

> > I'm having type issues due to trying to process ERC20 and ERC721 permits in the UI code (the schemas don't line up at all.)

> We should try and sync the properties as much as possible. I'm working on that now on my branch. I hope that it won't cause issues but I'm looking for input on constraints for the property names. 

> From what I understand if we change the property names then the old permits will be incompatible.

> @whilefoo why not just copy the schema as much as possible of ERC20 permits to the ERC721 permits?

_Originally posted by @pavlovcik in https://github.com/ubiquity/pay.ubq.fi/pull/146#discussion_r1498792922_

**Comment by Keyrxng** [comment]
So as far as I understand it, so long as we maintain the ``permitTransferFrom`` type in both nothing should break. 

- ERC721 recovers against the ``request`` object final hash
- ERC20 recovers against the ``PermitTransferFrom`` object

- I've had to hardcode a working sig for now as I've been unable to successfully generate it on the fly for some reason (tried many different ways but cannot generate a valid sig through the script, so input there would be appreciated. (all parts where identical))

The txData (what gets base64 encoded) can be arbitrary as it's not the txData object that's signed against but parts of it.

When building the tally-cli, I noticed a fair few different permit structures although I'm confident that updating the txData object (applying networkId and type etc, for me at least) my broken links were fixed in [unspent permits](https://github.com/Keyrxng/ubq-airdrop-cli/blob/master/src/unspent/unspentPermits.json). 

Maybe I'm missing the point, what is the fear with backwards compatibility? The actual signed ``PermitTransferFrom`` is the source of truth while everything else is metadata for the UI no? 

- [ERC721Permit](https://github.com/ubq-testing/pay.ubq.fi/blob/8693e52e162e3aad4ad2ca744d7ef42966f1f985/static/scripts/rewards/render-transaction/tx-type.ts#L43)

https://github.com/ubiquity/.github/assets/106303466/e6902c4f-5bfa-4ece-a6d7-589d280b0918

**Comment by pavlovcik** [comment]
> I've had to hardcode a working sig for now as I've been unable to successfully generate it on the fly for some reason (tried many different ways but cannot generate a valid sig through the script, so input there would be appreciated. (all parts where identical))

@Whilefoo @rndquu rfc

**Comment by Keyrxng** [comment]
So long as the schemas have always incorporated the ``PermitTransferFrom`` which I believe they have this should be pretty straightforward, in terms of UI's we just need to force previous permits to conform and nothing will break as the actual signed data has always adhered to the ``permit2-sdk``. 

Is the issue with backwards compatibility related to the metadata more so than the signature data, I'm assuming it's the sig data?

**Comment by Keyrxng** [comment]
- https://github.com/Keyrxng/ts-template/tree/permit-module
- https://github.com/ubq-testing/bot-ai/issues/26#issuecomment-1962382873

temporary (maybe not) solution for the permit module at least for simple testing

> Designing a robust and sensible schema for all permits in our system.

If I'm understanding right and the compatibility issues are based on the metadata surrounding the signed tx details, then this is done basically

> Updating the code across all of our repositories. This will require updating the database to accommodate the updated schema as well.

As for updating the DB the ERC20 schema hasn't changed and the ERC721 structure is a duplicate of within the ``nftMetadata`` and ``request`` objects appended. I'm unsure what the best way to update the DB schema would be

- pay.ubq.fi interface: Working 
- audits app: Working 
- nft-rewards repository: Working as required as part of pay UI QA video
- the UbiquiBot permit generation code: haven't tried the new permit shape but the module is working for ERC20, will finish up in the next day or so

Once I've verified that the module can create ERC721 permits and then those permits can be claimed via the portal then that's the majority of this task complete isn't it? I'll open PRs on each repo I've touched and link them all back to this?

**Comment by pavlovcik** [comment]
I'm expecting that we need to update the schema on the NFT smart contract and redeploy as well.

**Comment by Keyrxng** [comment]
Not necessarily, only the ``request`` part of the base64 txData is signed on chain for the reward NFT

``getMintDigest()`` returns a hash of the ``MintRequest`` struct which is signed and the sig is injected into the final txData which gets base64'd 

The UI needs the ERC721 permit to adhere to the signed part of the ERC20 txData in order to unwrap it but including it in the txData when the permit is generated doesn't affect what's being signed onchain

So unless you want to include more  of the metadata to what's being signed then it doesn't have to change

In regards to backwards compatibility, with the airdrop-cli it should be easy to bundle all unspent transactions then add the missing metadata the UI needs with new urls or roll them all into one new shape permit

Was the NFT-rewards contract part of the Sherlock audit?

**Comment by pavlovcik** [comment]
> Was the NFT-rewards contract part of the Sherlock audit?

No just Dollar related contracts.

**Comment by Keyrxng** [comment]
I think something has went awry with this one seeing as the associated PR was merged 2 weeks ago

**Comment by rndquu** [comment]
> I think something has went awry with this one seeing as the associated PR was merged 2 weeks ago

Was [this](https://github.com/ubiquity/pay.ubq.fi/pull/177) PR merged in our other repos mentioned in [this](https://github.com/ubiquity/pay.ubq.fi/pull/177#issuecomment-1976045628) comment?

**Comment by Keyrxng** [comment]
> > I think something has went awry with this one seeing as the associated PR was merged 2 weeks ago
> 
> Was [this](https://github.com/ubiquity/pay.ubq.fi/pull/177) PR merged in our other repos mentioned in [this](https://github.com/ubiquity/pay.ubq.fi/pull/177#issuecomment-1976045628) comment?

I do believe so Paul had me apply the changes soon after merge

- https://github.com/ubiquity/pay.ubq.fi/pull/186
- https://github.com/ubiquity/audit.ubq.fi/commit/4181d261a20cb14b732a3f1f595b1d44c1e2d983
- https://github.com/ubiquity/onboard.ubq.fi/pull/14

There is no usage of any permit types in `onboarding` as far as I can tell. The `/rewards` dir still existed but I've just opened a PR to purge that.

**Comment by rndquu** [comment]
> > > I think something has went awry with this one seeing as the associated PR was merged 2 weeks ago
> > 
> > 
> > Was [this](https://github.com/ubiquity/pay.ubq.fi/pull/177) PR merged in our other repos mentioned in [this](https://github.com/ubiquity/pay.ubq.fi/pull/177#issuecomment-1976045628) comment?
> 
> I do believe so Paul had me apply the changes soon after merge
> 
> * [chore: remove other apps, update readme pay.ubq.fi#186](https://github.com/ubiquity/pay.ubq.fi/pull/186)
> * [ubiquity/audit.ubq.fi@4181d26](https://github.com/ubiquity/audit.ubq.fi/commit/4181d261a20cb14b732a3f1f595b1d44c1e2d983)
> 
> There is no usage of any permit types in `onboarding` as far as I can tell. The `/rewards` dir still existed but I've just opened a PR to purge that.

Did you get the permit reward for this issue? It was closed (as far as I remember) and reopened later but I don't see any permit URLs
